version: 2
jobs:
  swiftlint:
    docker:
      - image: norionomura/swiftlint 
    steps:
      - checkout
      - run: swiftlint
  tests:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: swift test


workflows:
  version: 2
  lint:
    jobs:
      - swiftlint
      - tests
