version: 2
jobs:
  swiftlint:
    docker:
      - image: norionomura/swiftlint 
    steps:
      - checkout
      - run: swiftlint
  tests:
    build:
      macos:
        xcode: "9.3"
    steps:
      - checkout
      - run: swift test


workflows:
  version: 2
  lint:
    jobs:
      - swiftlint
      - tests
