version: 2
jobs:
  swiftlint:
    docker:
      - image: norionomura/swiftlint 
    steps:
      - checkout
      - run: swiftlint
  tests:
    macos:
      xcode: "9.2.1"
    steps:
      - checkout
      - run: swift test
  docs:
    macos:
      xcode: "9.2.1"
    steps:
      - checkout
      - run:
          name: Docs
          command: |
            brew install jazzy
            git checkout gh-pages
            git show master:README.md > README.md
            jazzy
            git config --global user.email "docs@nextdoor.com"
            git config --global user.name "Docs"
            git add README.md docs && git commit -m "Update docs [ci skip]" && git push origin gh-pages -f

workflows:
  version: 2
  corridor:
    jobs:
      - swiftlint
      - tests
      - docs
